;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/_AI/AI_New/DB/DT_Alian_Motivation.DT_Alian_Motivation
+GameplayTagTableList=/Game/_AI/AI_New/DB/DT_Test_Tag.DT_Test_Tag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="EnemyTag",DevComment="")
+GameplayTagList=(Tag="EnemyTag.Attack",DevComment="")
+GameplayTagList=(Tag="EnemyTag.Firing",DevComment="")
+GameplayTagList=(Tag="EnemyTag.HasTarget",DevComment="")
+GameplayTagList=(Tag="EnemyTag.HasTarget.SeeTarget",DevComment="")
+GameplayTagList=(Tag="EnemyTag.Search",DevComment="")
+GameplayTagList=(Tag="EnemyTag.Search.RandomMove",DevComment="")

